# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-30 01:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(error_messages={'min_length': 'El campo "Nombre" debe tener al menos %(limit_value)d caracteres (actualmente tiene %(show_value)d).'}, max_length=128, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='nombres')),
                ('last_name', models.CharField(error_messages={'min_length': 'El campo "Apellidos" debe tener al menos %(limit_value)d caracteres (actualmente tiene %(show_value)d).'}, max_length=128, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si el usuario puede entrar en este sitio de administración.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario puede ser tratado como activo. Desmarque esta opción en lugar de borrar la cuenta.', verbose_name='Activo')),
                ('address', models.CharField(blank=True, max_length=80, null=True, verbose_name='dirección')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=50, verbose_name='spanish name')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='spanish description')),
                ('name_en', models.CharField(max_length=50, verbose_name='english name')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='english description')),
            ],
            options={
                'ordering': ('name_es',),
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Phone number')),
                ('apply_jobs', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='¿Deseas aplicar a ofertas de trabajo publicadas en tus sectores de interés?')),
                ('email_jobs_notifications', models.BooleanField(default=True, verbose_name='Recibir notificaciones de ofertas e trabajo via e-mail.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.PositiveSmallIntegerField(choices=[(10, 'Invitación a administrar empresa')])),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('was_seen', models.BooleanField(default=False)),
                ('answered', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='account.ProfessionalProfile', verbose_name='creada por')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
