# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 19:22
from __future__ import unicode_literals

import app.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('avatar', models.ImageField(blank=True, max_length=255, upload_to='', validators=[app.validators.FileSizeValidator(4000)], verbose_name='profile image')),
                ('first_name', models.CharField(error_messages={'min_length': 'El campo "Nombre" debe tener al menos %(limit_value)d caracteres (actualmente tiene %(show_value)d).'}, max_length=128, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name')),
                ('last_name', models.CharField(error_messages={'min_length': 'El campo "Apellidos" debe tener al menos %(limit_value)d caracteres (actualmente tiene %(show_value)d).'}, max_length=128, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('address', models.CharField(blank=True, max_length=80, null=True, verbose_name='address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('accepted_terms', models.BooleanField(default=True, verbose_name='accepted user agreement')),
                ('accepted_terms_date', models.DateField(blank=True, null=True, verbose_name='accepted user agreement date')),
                ('accepted_privacy_policy', models.BooleanField(default=True, verbose_name='accepted privacy policy')),
                ('accepted_privacy_policy_date', models.DateField(blank=True, null=True, verbose_name='accepted privacy policy date')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('company',),
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=50, verbose_name='Spanish name')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Spanish description')),
                ('name_en', models.CharField(max_length=50, verbose_name='English name')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='English description')),
            ],
            options={
                'ordering': ('name_en',),
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_en', models.TextField(blank=True, verbose_name='English description')),
                ('description_es', models.TextField(blank=True, verbose_name='Spanish description')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Phone number')),
                ('email_jobs_notifications', models.BooleanField(default=True, verbose_name='receive notifications of job offers')),
                ('email_messages_notifications', models.BooleanField(default=True, verbose_name='receive notifications of new messages')),
                ('new_applicants_notifications', models.BooleanField(default=True, verbose_name='receive notifications of new applicants to job offers')),
                ('new_company_messages_notifications', models.BooleanField(default=True, verbose_name='receive notifications when companies I manage receive messages from users')),
                ('new_company_scores_notifications', models.BooleanField(default=True, verbose_name='receive notifications when companies I manage receive scores from users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('has_new_messages', models.BooleanField(default=False, verbose_name='has new messages')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('user_contact',),
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unread', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.PositiveSmallIntegerField(choices=[(10, 'Invitation to administer company.'), (20, 'New job offer that may interest you.'), (30, 'New applicants to my job offer.'), (40, 'New message to company.'), (50, 'New company score.'), (60, 'New user agreement.'), (70, 'New company score.')])),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('was_seen', models.BooleanField(default=False)),
                ('answered', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='account.ProfessionalProfile', verbose_name='created by')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
