# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-30 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170930_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='slug',
            field=models.SlugField(default='default-empty-slug'),
            preserve_default=False,
        ),
    ]
