# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_professionalprofile_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrycategory',
            options={'ordering': ('name_en',)},
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Invitation to administer company.')]),
        ),
    ]
