# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-14 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180609_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Invitation to administer company.'), (20, 'New job offer that may interest you.'), (30, 'New applicants to my job offer.'), (40, 'New message to company.'), (50, 'New company score.'), (60, 'New user agreement.'), (70, 'New company score.'), (80, 'Old job offer has been closed.'), (90, 'Company has been deactivated.'), (100, 'Company has been deleted.'), (110, 'Company has been transfered.')]),
        ),
    ]
