# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-06 14:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171218_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalprofile',
            old_name='description',
            new_name='description_en',
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'min_length': 'El campo "Nombre" debe tener al menos %(limit_value)d caracteres (actualmente tiene %(show_value)d).'}, max_length=128, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(error_messages={'min_length': 'El campo "Apellidos" debe tener al menos %(limit_value)d caracteres (actualmente tiene %(show_value)d).'}, max_length=128, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='last name'),
        ),
    ]
