# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180106_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='apply_jobs',
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Invitation to administer company.'), (20, 'New job offer that may interest you.')]),
        ),
    ]
