# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0009_auto_20180112_1606'),
        ('account', '0006_auto_20180122_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='job_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepreneur.JobOffer', verbose_name='related job offer'),
        ),
    ]
