# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_usernotification_job_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='account.ProfessionalProfile', verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='noty_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Notify to'),
        ),
    ]
