# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 19:56
from __future__ import unicode_literals

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_usermessage_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, upload_to='', validators=[app.validators.FileSizeValidator(4000)], verbose_name='profile image'),
        ),
    ]
