# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='email_messages_notifications',
            field=models.BooleanField(default=True, verbose_name='receive notifications of new messages'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='email_jobs_notifications',
            field=models.BooleanField(default=True, verbose_name='receive notifications of job offers'),
        ),
    ]
