# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180207_0235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='industrycategory',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='English description'),
        ),
        migrations.AlterField(
            model_name='industrycategory',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Spanish description'),
        ),
        migrations.AlterField(
            model_name='industrycategory',
            name='name_en',
            field=models.CharField(max_length=50, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='industrycategory',
            name='name_es',
            field=models.CharField(max_length=50, verbose_name='Spanish name'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='English description'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Spanish description'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
