# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 02:30
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20180315_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'min_length': 'El campo "Nombre" debe tener al menos %(limit_value)d caracteres (actualmente tiene %(show_value)d).'}, max_length=128, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(error_messages={'min_length': 'El campo "Apellidos" debe tener al menos %(limit_value)d caracteres (actualmente tiene %(show_value)d).'}, max_length=128, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
