# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180316_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='new_applicants_notifications',
            field=models.BooleanField(default=True, verbose_name='receive notifications of new applicants to job offers'),
        ),
    ]
