# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_professionalprofile_new_applicants_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='account.ProfessionalProfile', verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Invitation to administer company.'), (20, 'New job offer that may interest you.'), (30, 'New applicants to my job offer.')]),
        ),
    ]
