# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0019_auto_20180329_1542'),
        ('account', '0017_auto_20180329_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneur.Venture')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ProfessionalProfile', verbose_name='owner')),
            ],
            options={
                'ordering': ('company',),
            },
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_book_owner', to='account.ProfessionalProfile', verbose_name='owner')),
                ('user_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ProfessionalProfile', verbose_name='contact')),
            ],
            options={
                'ordering': ('user_contact',),
            },
        ),
    ]
