# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-07 00:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0019_auto_20180329_1542'),
        ('account', '0018_companycontact_usercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='company_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_to', to='entrepreneur.Venture', verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL, verbose_name='to'),
        ),
    ]
