# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-07 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0019_auto_20180329_1542'),
        ('account', '0019_auto_20180407_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='venture_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venture_to', to='entrepreneur.Venture', verbose_name='venture to'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Invitation to administer company.'), (20, 'New job offer that may interest you.'), (30, 'New applicants to my job offer.'), (40, 'New message to company.')]),
        ),
    ]
