# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20180407_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='new_company_messages_notifications',
            field=models.BooleanField(default=True, verbose_name='receive notifications when companies I manage receive messages from users'),
        ),
    ]
