# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0019_auto_20180329_1542'),
        ('account', '0021_professionalprofile_new_company_messages_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='company_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_from', to='entrepreneur.Venture', verbose_name='from'),
        ),
    ]
