# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-25 23:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0019_auto_20180329_1542'),
        ('account', '0022_usermessage_company_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField()),
                ('participating_company', models.ManyToManyField(to='entrepreneur.Venture')),
                ('participating_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
