# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-25 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='Conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Conversation'),
            preserve_default=False,
        ),
    ]
