# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20180426_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='participating_company',
        ),
    ]
