# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0019_auto_20180329_1542'),
        ('account', '0026_remove_conversation_participating_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='participating_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entrepreneur.Venture'),
            preserve_default=False,
        ),
    ]
