# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_conversation_participating_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participating_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepreneur.Venture'),
        ),
    ]
