# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20180426_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='Conversation',
            new_name='conversation',
        ),
    ]
