# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20180426_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='has_new_messages',
            field=models.BooleanField(default=False, verbose_name='has new messages'),
        ),
    ]
