# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-12 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_professionalprofile_has_new_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='new_company_scores_notifications',
            field=models.BooleanField(default=True, verbose_name='receive notifications when companies I manage receive scores from users'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Invitation to administer company.'), (20, 'New job offer that may interest you.'), (30, 'New applicants to my job offer.'), (40, 'New message to company.'), (50, 'New company score.')]),
        ),
    ]
