# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20180526_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_privacy_policy',
            field=models.BooleanField(default=True, verbose_name='accepted privacy policy'),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_privacy_policy_date',
            field=models.DateField(blank=True, null=True, verbose_name='accepted privacy policy date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='accepted_terms',
            field=models.BooleanField(default=True, verbose_name='accepted user agreement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='accepted_terms_date',
            field=models.DateField(blank=True, null=True, verbose_name='accepted user agreement date'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Invitation to administer company.'), (20, 'New job offer that may interest you.'), (30, 'New applicants to my job offer.'), (40, 'New message to company.'), (50, 'New company score.'), (60, 'New user agreement.'), (70, 'New company score.')]),
        ),
    ]
