# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporativeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sp', models.CharField(max_length=50, verbose_name='título')),
                ('title_en', models.CharField(max_length=50, verbose_name='title')),
                ('description_sp', models.TextField(verbose_name='descripción')),
                ('description_en', models.TextField(verbose_name='description')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'ítem informativo',
                'verbose_name_plural': 'ítems informativos',
                'ordering': ('id',),
            },
        ),
    ]
