# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 01:59
from __future__ import unicode_literals

from django.db import migrations


items = [
    {
        'title_sp': 'Política de privacidad',
        'title_en': 'Privacy policy',
        'description_sp': 'Default',
        'description_en': 'Default',
        'slug': 'privacy_policy',
    },
    {
        'title_sp': 'Términos de uso',
        'title_en': 'User agreement',
        'description_sp': 'Default',
        'description_en': 'Default',
        'slug': 'user_agreement',
    },
]


def generate_initial_info(apps, schema_editor):
    CorporativeInfoModel = apps.get_model('corporative', 'CorporativeInfo')

    for item in items:
        obj = CorporativeInfoModel(**item)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('corporative', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_initial_info),
    ]
