# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporative', '0002_auto_20171013_0214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorporativeInfo',
        ),
    ]
