# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporative', '0003_delete_corporativeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_title', models.CharField(max_length=50, verbose_name='Spanish title')),
                ('en_title', models.CharField(max_length=50, verbose_name='English title')),
                ('sp_description', models.TextField(blank=True, null=True, verbose_name='Spanish description')),
                ('en_description', models.TextField(blank=True, null=True, verbose_name='English description')),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Legal item',
                'verbose_name_plural': 'Legal items',
                'ordering': ('-updated_at',),
            },
        ),
    ]
