# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 22:54
from __future__ import unicode_literals

from django.db import migrations
from datetime import datetime, timedelta


legal_items = [
    {
        'slug': 'user-agreement',
        'sp_title': 'Términos de Uso',
        'en_title': 'User agreement',
        'updated_at': datetime.now() - timedelta(days=160),
    },
    {
        'slug': 'privacy-policy',
        'sp_title': 'Política de Privacidad',
        'en_title': 'Privacy Policy',
        'updated_at': datetime.now() - timedelta(days=160),
    },
    {
        'slug': 'cookies-policy',
        'sp_title': 'Política de Cookies',
        'en_title': 'Cookies Policy',
        'updated_at': datetime.now() - timedelta(days=160),
    },
]


def create_legal_items(apps, schema_editor):
    LegalItemModel = apps.get_model('corporative', 'LegalItem')

    for item in legal_items:
        i = LegalItemModel(**item)
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('corporative', '0005_legalitem_slug'),
    ]

    operations = [
        migrations.RunPython(create_legal_items),
    ]
