OWNER = 10
QJANE_ADMIN = 20
QJANE_SELLER = 30

ADMINISTRATOR_ROLES = (
    (OWNER, 'Owner'),
    (QJANE_ADMIN, 'Administrator'),
)


SENT_INVITATION = 10
ACTIVE_MEMBERSHIP = 20
DEACTIVATED_MEMBERSHIP = 30
REJECTED_MEMBERSHIP = 40

MEMBERSHIP_STATUS_CHOICES = (
    (SENT_INVITATION, 'Pending membership'),
    (ACTIVE_MEMBERSHIP, 'Active membership'),
    (DEACTIVATED_MEMBERSHIP, 'Inactive membership'),
    (REJECTED_MEMBERSHIP, 'Rejected membership'),
)
