OWNER = 10
QJANE_ADMIN = 20
QJANE_SELLER = 30

ADMINISTRATOR_ROLES = (
    (OWNER, 'Owner'),
    (QJANE_ADMIN, 'Administrator'),
)


SENT_INVITATION = 10
ACTIVE_MEMBERSHIP = 20
DEACTIVATED_MEMBERSHIP = 30
REJECTED_MEMBERSHIP = 40

MEMBERSHIP_STATUS_CHOICES = (
    (SENT_INVITATION, 'Pending membership'),
    (ACTIVE_MEMBERSHIP, 'Active membership'),
    (DEACTIVATED_MEMBERSHIP, 'Inactive membership'),
    (REJECTED_MEMBERSHIP, 'Rejected membership'),
)

VENTURE_STATUS_ACTIVE = 100
VENTURE_STATUS_INACTIVE = 120
VENTURE_STATUS_HIDDEN = 130

VENTURE_STATUS_CHOICES = (
    (VENTURE_STATUS_ACTIVE, 'Active'),
    (VENTURE_STATUS_INACTIVE, 'Inactive'),
    (VENTURE_STATUS_HIDDEN, 'Hidden'),
)

JOB_STATUS_ACTIVE = 100
JOB_STATUS_CLOSED = 120
JOB_STATUS_HIDDEN = 130

JOB_STATUS_CHOICES = (
    (JOB_STATUS_ACTIVE, 'Active'),
    (JOB_STATUS_CLOSED, 'Closed'),
    (JOB_STATUS_HIDDEN, 'Hidden'),
)


FREELANCE = 100
FULL_TIME = 110
INTERNSHIP = 120
PART_TIME = 130
TEMPORARY = 140
VOLUNTEER = 150

JOB_TYPE_CHOICES = (
    (FREELANCE, 'Freelance'),
    (FULL_TIME, 'Full time'),
    (INTERNSHIP, 'Internship'),
    (PART_TIME, 'Part time'),
    (TEMPORARY, 'Temporary'),
    (VOLUNTEER, 'Volunteer'),
)
