# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-30 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Invitación pendiente'), (20, 'Membresía activa'), (30, 'Membresía inactiva'), (40, 'Membresía rechazada')], default=10)),
                ('role', models.PositiveSmallIntegerField(choices=[(10, 'Administrador general'), (20, 'Administrador')], default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ProfessionalProfile', verbose_name='Administrador')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_owner', to='account.ProfessionalProfile', verbose_name='Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico de contacto')),
                ('is_main', models.BooleanField(default=False, verbose_name='Principal')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='teléfono de contacto')),
                ('is_main', models.BooleanField(default=False, verbose_name='Principal')),
            ],
        ),
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('logo', models.ImageField(blank=True, help_text='150x150', max_length=255, upload_to='uploads/ventures/')),
                ('description_es', models.TextField(verbose_name='descripción')),
                ('description_en', models.TextField(verbose_name='description')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='dirección')),
                ('url', models.URLField(blank=True, verbose_name='Página web')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Página de Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Página de Twitter')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Página de Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Página de Linkedin')),
                ('googleplus_url', models.URLField(blank=True, verbose_name='Página de Google +')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.City', verbose_name='city')),
                ('contact_emails', models.ManyToManyField(blank=True, to='entrepreneur.ContactEmail')),
                ('contact_phones', models.ManyToManyField(blank=True, to='entrepreneur.ContactPhone')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Country', verbose_name='country')),
                ('industry_categories', models.ManyToManyField(to='account.IndustryCategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ProfessionalProfile', verbose_name='Creada por')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.State', verbose_name='state')),
            ],
        ),
        migrations.AddField(
            model_name='administratormembership',
            name='venture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneur.Venture', verbose_name='Empresa'),
        ),
    ]
