# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-14 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venture',
            name='point',
        ),
        migrations.AlterField(
            model_name='venture',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place.City', verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venture',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place.Country', verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venture',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place.State', verbose_name='state'),
            preserve_default=False,
        ),
    ]
