# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 01:01
from __future__ import unicode_literals

from django.db import migrations


initial_categories = [
    {
        'name_es': 'Dispensario',
        'name_en': 'Dispensary',
    },
    {
        'name_es': 'Cañamo',
        'name_en': 'Hemp',
    },
    {
        'name_es': 'Cultivo',
        'name_en': 'Cultivation',
    },
    {
        'name_es': 'Medicinal',
        'name_en': 'Medical',
    },
]


def create_initial_industry_categories(apps, schema_editor):
    IndustryCategoryModel = apps.get_model('account', 'IndustryCategory')

    for category in initial_categories:
        i = IndustryCategoryModel(**category)
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_industry_categories),
    ]
