# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-04 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0002_auto_20170930_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venture',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Country', verbose_name='país'),
        ),
    ]
