# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-09 18:30
from __future__ import unicode_literals

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0004_venture_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venture',
            name='contact_emails',
        ),
        migrations.RemoveField(
            model_name='venture',
            name='contact_phones',
        ),
        migrations.AddField(
            model_name='venture',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo electrónico de contacto'),
        ),
        migrations.AddField(
            model_name='venture',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='logo',
            field=models.ImageField(blank=True, help_text='150x150', max_length=255, upload_to='uploads/ventures/', validators=[app.validators.FileSizeValidator(4000)]),
        ),
        migrations.DeleteModel(
            name='ContactEmail',
        ),
        migrations.DeleteModel(
            name='ContactPhone',
        ),
    ]
