# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 04:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0005_auto_20171009_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratormembership',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ProfessionalProfile', verbose_name='Administrator'),
        ),
        migrations.AlterField(
            model_name='administratormembership',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_owner', to='account.ProfessionalProfile', verbose_name='Administrator'),
        ),
        migrations.AlterField(
            model_name='administratormembership',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Owner'), (20, 'Administrator')], default=20),
        ),
        migrations.AlterField(
            model_name='administratormembership',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Pending membership'), (20, 'Active membership'), (30, 'Inactive membership'), (40, 'Rejected membership')], default=10),
        ),
        migrations.AlterField(
            model_name='administratormembership',
            name='venture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneur.Venture', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='description_en',
            field=models.TextField(verbose_name='english description'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='description_es',
            field=models.TextField(verbose_name='spanish description'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook url'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='googleplus_url',
            field=models.URLField(blank=True, verbose_name='Google plus url'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram url'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='Linkedin url'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ProfessionalProfile', verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='contact phone'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter url'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='url',
            field=models.URLField(blank=True, verbose_name='webpage'),
        ),
    ]
