# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 22:40
from __future__ import unicode_literals

import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_auto_20171004_2232'),
        ('entrepreneur', '0006_auto_20171218_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='title (position)')),
                ('slug', models.SlugField()),
                ('description', models.TextField(verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.City', verbose_name='city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Country', verbose_name='country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.State', verbose_name='state')),
            ],
        ),
        migrations.AlterField(
            model_name='venture',
            name='logo',
            field=models.ImageField(blank=True, help_text='150x150', max_length=255, upload_to='', validators=[app.validators.FileSizeValidator(4000)]),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='venture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrepreneur.Venture', verbose_name='company'),
        ),
    ]
