# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180106_1418'),
        ('entrepreneur', '0007_auto_20180108_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='industry_categories',
            field=models.ManyToManyField(to='account.IndustryCategory'),
        ),
    ]
