# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0008_joboffer_industry_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ('-created_at',), 'verbose_name': 'job offer', 'verbose_name_plural': 'job offers'},
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='venture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneur.Venture', verbose_name='company'),
        ),
    ]
