# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0010_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='job_type',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Freelance'), (110, 'Full time'), (120, 'Internship'), (130, 'Part time'), (140, 'Temporary'), (150, 'Volunteer')], default=100, verbose_name='job type'),
        ),
    ]
