# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0012_auto_20180305_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Active'), (120, 'Closed'), (130, 'Hidden')], default=100, verbose_name='status'),
        ),
    ]
