# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0014_auto_20180306_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Activo'), (120, 'Closed'), (130, 'Hidden')], default=100, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Activo'), (120, 'Inactivo'), (130, 'Hidden')], default=100, verbose_name='estado'),
        ),
    ]
