# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0015_auto_20180315_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Active'), (120, 'Closed'), (130, 'Hidden')], default=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Active'), (120, 'Inactive'), (130, 'Hidden')], default=100, verbose_name='status'),
        ),
    ]
