# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0016_auto_20180316_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venture',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='english description'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='spanish description'),
        ),
    ]
