# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0018_joboffer_applicants_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='applicants_record',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='applicants register'),
        ),
    ]
