# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0019_auto_20180329_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='venture',
            name='has_new_messages',
            field=models.BooleanField(default=False, verbose_name='has new messages'),
        ),
    ]
