# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 20:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrepreneur', '0020_venture_has_new_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneur.Venture', verbose_name='company')),
            ],
        ),
    ]
