# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0021_companyscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyscore',
            old_name='venture',
            new_name='company',
        ),
    ]
