# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-11 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0024_companyscore_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
