# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-03 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('country',), 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default=1, max_length=2, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
