# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-04 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20171003_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, unique=True),
        ),
    ]
