# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-04 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20171004_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
    ]
