# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-04 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_remove_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
