# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-04 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place.Country', verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place.Country', verbose_name='country'),
            preserve_default=False,
        ),
    ]
